# Year when the wind park is put into commercial operation is renamed to phase
commercial_operation_year_to_phase = {'1998': 'I',
                                      '1999': 'II',
                                      '2000': 'III',
                                      '2001': 'IV',
                                      '2002': 'V',
                                      '2003': 'VI',
                                      '2004': 'VII',
                                      '2005': 'VIII',
                                      '2006': 'IX',
                                      '2007': 'X',
                                      '2008': 'XI',
                                      '2009': 'XII',
                                      '2010': 'XIII',
                                      '2011': 'XIV',
                                      '2012': 'XV',
                                      '2013': 'XVI',
                                      '2014': 'XVII',
                                      '2015': 'XVIII',
                                      '2016': 'XIX',
                                      '2017': 'XX',
                                      '2018': 'XXI',
                                      '2019': 'XXII'}
